# Generated by Django 5.0.7 on 2024-07-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('screen_size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'موجود'), ('unavailable', 'ناموجود')], default='available', max_length=11)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='mobile.brand')),
            ],
        ),
    ]
