# Generated by Django 5.0.7 on 2024-07-31 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True, verbose_name='مدل')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('screen_size', models.PositiveIntegerField(verbose_name='سایز صفحه نمایش')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('unavailable', 'ناموجود')], default='available', max_length=11, verbose_name='موجودی')),
                ('country_of_origin', models.CharField(max_length=50, verbose_name='کشور سازنده')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='mobile.brand', verbose_name='برند')),
            ],
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
