# Generated by Django 5.0.7 on 2024-07-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobile_delete_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سایز صفحه نمایش'),
        ),
    ]
