# Generated by Django 5.0.7 on 2024-08-03 16:05

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_mobile_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='datetime_modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
