# Generated by Django 5.0.7 on 2024-08-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_mobile_datetime_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiles', to='mobile.brand', verbose_name='برند'),
        ),
    ]
